language: node_js
node_js:
- '8'
script:
- yarn test
deploy:
  provider: heroku
  api_key:
    secure: T7aASLMwpkVEpkLCY8oPFVt4/9QKdIAuDNOA809M2FnsUE/QoJvk4dUl8Txi4KKT8xBoAfQGS955d87rDm1H0Aif0e7Sn75yM+ZhqgEcTcpJObOVH+monNjtkG3Zh7mrnQfm7Zvui5aN+6lXp5lHAaDBDCUerdBBhEo0G6zdd4Kis5KCqFDT6dHPl/WuZy6QxF2dkXhvX7uiBppEHGwLf0IFGf3xeBuZ45KNAfvVQVqntBzYuq4Znzmn5T94ENer8g480c04tLkiXfZH5a+iqNbJYJs8kHRugZtSTdFIkLVIBpvCXG3NMQAbu69XLGhjyBax2Q0wDoPUhka55KmY9p340pJIElqhjvLLqGGFrwXP9t+WlZOVjSHpf34xqXOAzP+vD6lrMrzDabXEbuZeNDHZ8PcfynyfY8VAGDyp6fNZNliYEkpQnSH6uFZ2F6G1njcsE1I49JVKqx5ppQJfF/rZjv3oz4rdCuCluwvavQrLR/11Iq/H6B6DOVK5sQrW3vWeHNDYIvIbTaejPov298POsfH+btHDoyw5dgYKx5AbeYZtFex7nF6kQb1HXROisqhxv4nQwFKFeoJzLSxALIRW/kL84dtopkd1/8eRNOxMjeo8H5qpP4A324slFYjBigVcDCPlcLqXMsya4KQkWItKr20aRK8UtPqBuWRjSHM=
  app: 
    master: classinsights
