language: node_js
node_js:
- '9.11'
script:
- yarn test
deploy:
  provider: heroku
  api_key:
    secure: lUqNfc4DRCSvofyVPbWENyByjt5MlihaMd7Ab7+j+v/J5Lo5hcwglcCB/cN4Ea9Vs+7CY9SYg5GB+QeUNQ0REcbLHxd1t4hBoEov2ELRK+GQPLwjZ2O5WMueGL7ODLgH94bYPb3e0iYbuD2++DjBV0IWbHLMmC/jX0IZNjRAICXZIOcwLMbAn4nBkH+NC3gS7DOW9A2aAa2oIPcQvejzoliwVzMppl+2Jslfafuf6AuDyO9fFC/5fn1i/99oGvWLGXZevoU2RG70+5dOFW4yYzRTiOc0xBKu06L+ulKsywp8xbRnPdxG1H5Jj/IDAsiZB24/7GEn9wYsQ/P1q3ZkE/1afXrtgE5DKfj/FYqW3bRPWJMsg5rK27aOV5FkBNZk//33J5p2ckGwSOSltwct2N/ahVulRk85oPS1y0umpDvqV36bi+wSGTSBk73ZYkwKA0Xt3uAfq+P5T6An9kYQJAA12Sj6bEUFGs4w+oXjFv86I2cq2MHJnlA410VOkpCMHZds2zoAAVrMErLWjkHs4SQ/J4FLt3kpv667izZlEHpe1et0FtEibX9YCUfTNPeBUTolk3gVV35SRp37o/ULu6mWpIGHra1slGqisL/mvsn+Fk7Nq71Cm93klzum86oYn94ggtppE9MmkPnFMyUg7eHQJYeTqmjcWY0BouJdD8g=
  app:
    master: classinsights
