language: node_js
node_js:
- '8'
script:
- yarn test
deploy:
  provider: heroku
  api_key:
    secure: N4wrUjEFEyexpcuFYvI9N1ax9LVd6PO++6sJdGEnBh6ALqq5EtDL/zDpmussyNQLP4NB2GPNNSe6JQnslAZ7oxgNWhAo9dIWJigm47CAJPKmPfk9Q7Tnr6rofcMR32Q2mjZZ8WnppoDgratWrcmCkP9yW9h8KdyAS7ftTjssOnSuRZWdAegCXd/gFuOaK13Ymkuxsm5O8VZGmnl9gJrP71n2RbalIAtrTD2Jxx4vFZYTNdVLoyf4SCMNGBYQqBsRJLYV9AD/XGbtAYlWjrbTiVgAmtlaarxOlpG3nhY5qVyj5EnOpTLq/biwcmrIcRkWmK22DGnWVWMonhQwNo9F8fZBGFldmFY6A7u/2mSE9FPgnyZB+EPehpjy3WWWzhek0YBMA+LXeuPsJfNJXIUfh844CJ64uidt5akrVZ6pxG3UKCX4LNspN1gYC0xxCKDrnOwco9B1DahbQnKWoJv75zbW2GhxeV4W7xq+LifM1zuFlJ+HkvX1UKrAH7CPro+CMtDzUioqwr4NSFeEv76812vbrJ2Iw+3pmwPSxij1NgYbC8xQQm0CU7y+/mwOo87uo0uv7kFkbU7+HKQnnwaZHXJoxJY5ilZ4gczGvGJx4idQmlhJYdckrIPdIdOfwLDiK62ym9amNxkJstjMDd8fOpA90Em7szUp1NNYqrpjeJQ=
  app:
    master: classinsights
