language: node_js
node_js:
- '8'
script:
- yarn test
deploy:
  provider: heroku
  api_key:
    secure: Qr9WpEk/G8oinVA5J+7Tou25KUJcgvAgAuh7e8FYDD8SOXTMDwElneh7deqlUW+3e7skJeW7pFwhBLXzMEPLxXz0LGyEV20EOZqBTVEmlzJ7Q0v6bTNbqiJMNs4EFWKZNuvg2dn1bpmSfHkUAWLh2w20lNmr+SKDZhvDTMxPIud5GWwCZAHclVTdd8RQ56QX+8XRm6rzKzeXM/a8unCH3P9xC6N53KCHs2qSrf9IQ7vT3EfPvQfJJijs3ycW3IEOm1AjdVJ7jv73hp9kvgA5ZHOj98VYA0XhvYlxbhvuqscFw5fUCoC139JjD5I9/4ja78lJAd/lhkePuCRmO4xGsD8RlHECKTjRy+r8C1aije4uqeKsC8Mhbg/tX7uWCLZ4TN/zKMpK1kKjqZXgek8x8qL4k60nWfq5gEGdRqNeoEVfgjH5yz8g5kQ/K/444nbnkX3je0DuiLK4D547OSorN7D8oXgwB3eDhCuP2zmvKN6Y7QjLSf70EGJrY5pOd7Evq4vsrcpo2H7IwhByb/nF59/acHTCq45JjSsnH53V8qFAlAypk6nZXBfMMUftRF22KuXMBmtFmVvou/Zmx9VdXRFFQIbReiMPFAEcxbM2bRaxNNjEJRzfgSb4s31wt+sq4Kgsfb6vi1E7zg6pPM5DcykLZTHlrC/JHSJ3ZMpB0WI=
  app:
    master: classinsights
